{"errorMessage": "An error occurred (dependencyFailedException) when calling the InvokeAgent operation: Dependency resource: received model timeout/error exception from Bedrock. Try the request again.", "errorType": "EventStreamError", "requestId": "4b6f9777-eb2b-4682-8b2f-80f5dcaef579", "stackTrace": ["  File \"/var/task/app.py\", line 54, in lambda_handler\n    raise e\n", "  File \"/var/task/app.py\", line 39, in lambda_handler\n    process_resume(bucket, key)\n", "  File \"/var/task/app.py\", line 217, in process_resume\n    raise e\n", "  File \"/var/task/app.py\", line 213, in process_resume\n    raise e\n", "  File \"/var/task/app.py\", line 152, in process_resume\n    for event in response['completion']:\n", "  File \"/var/lang/lib/python3.11/site-packages/botocore/eventstream.py\", line 592, in __iter__\n    parsed_event = self._parse_event(event)\n", "  File \"/var/lang/lib/python3.11/site-packages/botocore/eventstream.py\", line 608, in _parse_event\n    raise EventStreamError(parsed_response, self._operation_name)\n"]}